services:
  db-init:
    image: alpine:latest
    volumes:
      - db-data:/app/db
      - ./db/init.sql:/app/init.sql:ro
    command: >
      sh -c "
        mkdir -p /app/db &&
        if [ ! -f /app/db/connections.db ]; then
          echo 'Initializing database...' &&
          apk add --no-cache sqlite &&
          sqlite3 /app/db/connections.db < /app/init.sql &&
          echo 'Database initialized successfully'
        else
          echo 'Database already exists, skipping initialization'
        fi
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - db-data:/app/db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/db/connections.db
      - DATABASE_URL=jdbc:sqlite:/app/db/connections.db
    depends_on:
      db-init:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  db-data:
    driver: local
